Refactored build.yml to check 17

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,16 +1,21 @@
 
 #specify a trigger
 #on keyword triggers when we push a commit to repo
-on: push
+on:
+  push:
+  branches:
+    - main
+
 jobs:
-  first-job:
-    runs-on: macos-latest
+  build:
+    runs-on: macos-latest # Or your desired runner OS
+
     steps:
       - name: Check Java Version
         run: |
           echo "Java Version: $JAVA_HOME"
           java -version
-          if ! java -version 2>*1 | grep q "21.*"; then 
-            echo "Error: Java 21 is required!"
+          if ! java -version 2>&1 | grep -q "17.*"; then
+            echo "Error: Java 17 is required!"
             exit 1
           fi
