Updated to jdk 21

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,7 +10,7 @@ jobs:
         run: |
           echo "Java Version: $JAVA_HOME"
           java -version
-          if ! java -version 2>*1 | grep q "17.*"; then 
-            echo "Error: Java 17 is required!"
+          if ! java -version 2>*1 | grep q "21.*"; then 
+            echo "Error: Java 21 is required!"
             exit 1
           fi
